name: Get and write
on:
  [push]

jobs:
  get-and-write:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: chomd +x
    - run: mkdir /actions
    - run: touch /actions/application-secret.yml
    - run: echo ${{ secrets.APPLICATION_YML }} | base64 --decode >> /actions/application-secret.yml
