name: Get and write
on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Secret
        run: mkdir actions && touch actions/application-secret.yml && echo ${{ secrets.APPLICATION_YML }} | base64 --decode >> /actions/application-secret.yml
