name: Get and write
on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Copy Secret
        run: |
          mkdir -p src/main/resources
          echo ${{ secrets.APPLICAION_YML }} | base64 --decode >> src/main/resources/application-database.yml
